import getpass
import colorama
from colorama import Fore
import discord
from discord.ext import commands
import os
import getpass
client = commands.Bot(command_prefix=commands.when_mentioned_or("$"))

os.system(f'cls & mode 85,20 & title PHAZIFY AUTOPRESSER')
user = input("Name: ")
print(f'''{Fore.GREEN}
 _    __   __    __   ______   ________  ______  ________  __      __ 
|       \ |  \  |  \ /      \ |        \|      \|        \|  \    /  |
| $$$$$$$\| $$  | $$|  $$$$$$\ \$$$$$$$$ \$$$$$$| $$$$$$$$ \$$\  /  $$
| $$__/ $$| $$__| $$| $$__| $$    /  $$   | $$  | $$__      \$$\/  $$ 
| $$    $$| $$    $$| $$    $$   /  $$    | $$  | $$  \      \$$  $$  
| $$$$$$$ | $$$$$$$$| $$$$$$$$  /  $$     | $$  | $$$$$       \$$$$   
| $$      | $$  | $$| $$  | $$ /  $$___  _| $$_ | $$          | $$    
| $$      | $$  | $$| $$  | $$|  $$    \|   $$ \| $$          | $$    
 \$$       \$$   \$$ \$$   \$$ \$$$$$$$$ \$$$$$$ \$$           \$$    
             ___________LOGGED IN AS: {user}___________                                             
                        PHAZIFY MADE THIS
                                                                                    
        ''' + Fore.GREEN)

token = input("Enter token: ")
sex = input("Keyword: ")
print("READY TO RAPE BLACKS")
###### CODEZZZZZ#######
@client.event
async def on_message(message):
    channel = message.channel
    print("BITCH GOT RAPED:",message.content)
    if message.content.endswith(sex):

        await message.channel.send('LOOL MAJESTY HAS ARRIVED GET UR THROAT READY')
        await message.channel.send('🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪🔪')
        await message.channel.send('IM ONE OF THE SECEN PRINCES OF HELL')
        await message.channel.send('CHIEF DEMON IS READY TO SNAP UR NECK')
        await message.channel.send('LMAOO UR MOM HAS CHEMO IMAGINE L')
        await message.channel.send('LOL OLOLO LOOL LOLOOL BEG ME')
        await message.channel.send('BARK FOR ME AMPUTATED JEWISH BITCH WITHOUT ARMS AND LEGS')
        await message.channel.send('🐶🐶🐶🐶🐶🐶🐶')
        await message.channel.send('GET ON CHAT AND LET KKK BITCH YOUR SOUL')
        await message.channel.send('PHAZIFYY RUNS YOUR SOUL')
        await message.channel.send('PUT UR CLOCK DONT OVERSLEEP ON ME')
        await message.channel.send('UR MOM POURS POUR LIQUID ON HER ASS')
        await message.channel.send('Y O U  A R E  A  F A G G O T')
        await message.channel.send('YOU BELONG TO ME LITTLE BITCH')
        await message.channel.send('UR MOM ASS IMPECCABLY BEAUTIFUL')
        await message.channel.send('UR NAMED AFTER A FUCKING TRANNY')
        await message.channel.send('ILL PRESS UR DUMBASS TO THE FLOOR')
        await message.channel.send('🤓🤓🤓🤓')
        await message.channel.send('I RUN A LEGION OF DEMONS')
        await message.channel.send('FUCKING GOBLIN')
        await message.channel.send('LET ME PUT YOU IN A HEADLOCK')
        await message.channel.send('UR MOM HAS HAIRY NIPPLES ')
        await message.channel.send('💀💀💀💀💀💀')
        await message.channel.send('FEMINIST')
        await message.channel.send('ILL BURN A LGBTQ FLAG INSIDE UR SKIN')
        await message.channel.send('ILL DICK UR MOM DOWN')
        await message.channel.send('SAY CHEESE ')
        await message.channel.send('📸📸📸📸📸')
        await message.channel.send('UR MY GOON')
        await message.channel.send('NAKED MOLED RAT')
        await message.channel.send('🐀🐀🐀🐀🐀')
        await message.channel.send('MY SLAVE')
        await message.channel.send('KEEP OBEYING ME')
        await message.channel.send('DOG ON THE LEASH ')
        await message.channel.send('I RUN YOU')
        await message.channel.send('UR GIRLS OILED ASS IS THICK ASF')
        await message.channel.send('PRICK ASS')
        await message.channel.send('FUCKING WEAKLING')
        await message.channel.send('YOU CANT OUTCHAT THE PRINCE OF HELL')
        await message.channel.send('FAGGOTTT')
        await message.channel.send('COME GET BITCHED BY MY EMPIRE')
        await message.channel.send('LOLOL')
        await message.channel.send('OLOLOL')
        await message.channel.send('LOLOLOL')
        await message.channel.send('ILL CUT DOWN UR LEGS WITH A CHAINSAW')
        await message.channel.send('IM UR CHIEF LOO')
        await message.channel.send('IM THE MOST CRUEL NIGGA U EVER MET')
        await message.channel.send('COME GET BITCHED')
        await message.channel.send('LITLE THOT')
        await message.channel.send('GET UR WORDS OUT')
        await message.channel.send('ILL RAPE UR FAMILY TREE')
        await message.channel.send('ILL CURSE UR FAMILY FOR GENERATIONS')
        await message.channel.send('GET TO THE COTTON PICKING')
        await message.channel.send('123')
        await message.channel.send('456')
        await message.channel.send('789')
        await message.channel.send('KKK ON TOP')
        await message.channel.send('GIVE ME 10 PUSHUPS')
        await message.channel.send('YOUR MOM HAS BREAST CANCER')
        await message.channel.send('LOLOL ILL FACIAL BUST MY NUTS IN UR MOTHER')
        await message.channel.send('U SUCK')
        await message.channel.send('IM THE GREAT KING OF HELL')
        await message.channel.send('UR SO FUCKING UNKNOWN')
        await message.channel.send('UR MOM HAS A HEAD OF A OWL')
        await message.channel.send('GHETTO BITCH LOOL')
        await message.channel.send('IM UNFOLDABLE')
        await message.channel.send('ILL SLIDE A BLOODY TABON IN UR MOM')
        await message.channel.send('U HAVE LEUKEMIA')
        await message.channel.send('ILL BAKE THE FUCK OUT YOU')
        await message.channel.send('UR UNDER MY COMMMAND')
        await message.channel.send('UR POSSESSSED WITH A EVIL SPIRIT')
        await message.channel.send('LMAOAOAO')
        await message.channel.send('EZ')
        await message.channel.send('PRESSURING THIS BUM')
        await message.channel.send('FOCUS')
        await message.channel.send('COME TAKE THIS MONSTER BBC')
        await message.channel.send('ILL GIVE UR MOM ORAL')
        await message.channel.send('ONLYFANSS')
        await message.channel.send('DISABLED RETARD')
        await message.channel.send('PATHETIC')
        await message.channel.send('LET ME STOMP ON UR GRANDPAS GRAVE')
        await message.channel.send('CHECK UR MOMS MASTRUBATE VIDEO')
        await message.channel.send('LMAOAOAO')
        await message.channel.send('TOURETTE KID')
        await message.channel.send('KEEP MOCKING AND STUTTERING')
        await message.channel.send('LOOOL')
        await message.channel.send('LOLOL')
        await message.channel.send('FOLD?!')
        await message.channel.send('EAT SOME SYRIAN STREET FISH')
        await message.channel.send('WAKE UP FAGGOT')
        await message.channel.send('ILL SLAP A FISH IN UR FACE')
        await message.channel.send('U AINT SLEEPING')
        await message.channel.send('UR AUNT IS A SEXWORKER')
        await message.channel.send('9/11')
        await message.channel.send('https://zeenews.india.com/world/9/11-attacks-new-york-marks-19th-anniversary-of-the-dreadful-terror-attack-2308932.html')
        await message.channel.send('UR DAD DIED IN THERE LOOOL')
        await message.channel.send('HE HAD NO PARACHUTE')
        await message.channel.send('TAKE THIS BBC')
        await message.channel.send('GET IN THE ELECTRIC CHAIR')
        await message.channel.send('LET ME FRY UR BRAINS')
        await message.channel.send('LOOOL')
        await message.channel.send('DIPSHIT')
        await message.channel.send('INSIDE THE BODYBAG')
        await message.channel.send('LET ME CREMATE UR ASS')
        await message.channel.send('LOOO')
        await message.channel.send('LOOL')
        await message.channel.send('OOOOOOOOL')
        await message.channel.send('DRY LIPS?')
        await message.channel.send('USE SOME VASELINE FAGGOT')
        await message.channel.send('VIRGIN BOY')
        await message.channel.send('DISCORD HERO')
        await message.channel.send('😹😹😹😹😹😹😹')
        await message.channel.send('SHITTY FAGGOT')
        await message.channel.send('ILL SWAT YOU')
        await message.channel.send('LMAOAOA')
        await message.channel.send('UR GONNA BE MY PERSONAL SERVANT')
        await message.channel.send('SLEEP TIGHT')
        await message.channel.send('LOLO')
        await message.channel.send('OLO')
        await message.channel.send('LO')
        await message.channel.send('LOOLOO')
        await message.channel.send('OLOL')
        await message.channel.send('LOLO')
        await message.channel.send('LOLOL')
        await message.channel.send('UR SLOW')
        await message.channel.send('GET ON CHAT')
        await message.channel.send('UR PRESSURING IS SHIT')
        await message.channel.send('LOOL GET OFF UR NINTENDO SWITCH')
        await message.channel.send('SHITTER')
        await message.channel.send('WANT ME TO CLIP YOU?')
        await message.channel.send('BETTER START FOCUSING')
        await message.channel.send('WONT TAKE LONG BEFORE YOU BELONG TO ME')
        await message.channel.send('UN')
        await message.channel.send('STOPP')
        await message.channel.send('ABLE')
        await message.channel.send('LOOL')
        await message.channel.send('ILL BARBEQUE YOU ON THE SUN')
        await message.channel.send('SHITTY CUNT')
        await message.channel.send('TURN AROUND AND OBEY ME ON YOUR KNEES')
        await message.channel.send('OBSERVE ME')
        await message.channel.send('OBEY ME')
        await message.channel.send('ILL HANG YOU')
        await message.channel.send('BITCHED THE BLACK')
        await message.channel.send('OLOL ILL BOMB YOUR HOUSE')
        await message.channel.send('UR MOM GOT SLAGGY TITS')
        await message.channel.send('LET ME IMPREGNANT UR MOM THROUGH BLUETOOTH CONNECTION')
        await message.channel.send('ILL SPIT ON UR FACE')
        await message.channel.send('SHITTY RETARD')
        await message.channel.send('NAZI RUNS YOU')
        await message.channel.send('🔝🔝🔝🔝🔝🔝')
        await message.channel.send('USSR RUNS YOU')
        await message.channel.send('🔝🔝🔝🔝🔝🔝')
        await message.channel.send('KKK RUNS YOU')
        await message.channel.send('🔝🔝🔝🔝🔝🔝')
        await message.channel.send('CLONE URSELF LETS 2V1')
        await message.channel.send('DUCKING?')
        await message.channel.send('ILL CHOKE UR MOM WHILE SHE BLOWJOBS ME')
        await message.channel.send('ILL PULL HER HAIR')
        await message.channel.send('GOON')
        await message.channel.send('MY LITTLE SEED')
        await message.channel.send('FATHER')
        await message.channel.send('OUT')

client.run(token, bot=False)
